In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
a=np.array(10)
print(type(a))
a.ndim

<class 'numpy.ndarray'>


0

In [10]:
z=np.array([10,12,22,15]) #single Sq brackates
z.ndim

1

In [11]:
az=np.array([[10,22,12,15,17]]) #2 sq brackets

az.ndim

2

In [13]:
a=np.array([10,15,24,20],dtype='float') #change data type
print(a.dtype)
print(a)

float64
[10. 15. 24. 20.]



# Change Ways of creating an arrays

# - Arrays

In [15]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

 # - Linspace

In [24]:
b=np.linspace(1,5,retstep=True)
b

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
        1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
        1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
        2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
        2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
        3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
        3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
        3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
        4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
        4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]),
 0.08163265306122448)

# - Zeros And Once

In [25]:
z=np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [26]:
o=np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

# - Random

In [28]:
r=np.random.rand(5,5) #generate the random number od arrays
r 

array([[0.96320374, 0.25412244, 0.09109699, 0.5825211 , 0.0896532 ],
       [0.65465203, 0.77888518, 0.78357994, 0.22012167, 0.20701084],
       [0.18770699, 0.2291578 , 0.04398149, 0.42570349, 0.14961379],
       [0.46534914, 0.47854956, 0.78193131, 0.25384531, 0.1801078 ],
       [0.5195749 , 0.99498017, 0.64482723, 0.18326129, 0.32359919]])

In [29]:
r=np.random.randint(5,size=10)
r

array([0, 3, 3, 2, 3, 2, 2, 1, 1, 3])

# -Slicing And Indexing

In [30]:
a=np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a[0,0]

1

In [32]:
a[1,2]

6

In [33]:
a[0,1:]

array([2, 3])

In [34]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a[[0,1],[0,2]] #a[[rowindex[1],rowindex[6]],[colindex[1],colindex[6]]]

array([1, 6])

In [38]:
a[[0,1],[2,0]]

array([3, 4])

# -Reshaping the arrays

In [43]:
a=np.array([[1,2,3,4,5],[1,10,5,14,60]])
a

array([[ 1,  2,  3,  4,  5],
       [ 1, 10,  5, 14, 60]])

In [45]:
a.ndim

2

In [46]:
a.shape

(2, 5)

In [52]:
a=np.random.rand(5,2)

In [53]:
a

array([[0.33045311, 0.54236473],
       [0.98888095, 0.09991401],
       [0.12295545, 0.65640803],
       [0.97131467, 0.08107003],
       [0.54513167, 0.72490344]])

In [62]:
a.reshape(2,5) #Reshape the array here 2*5, 5*2, 10*1, 1*10 like this can reshape

array([[0.33045311, 0.54236473, 0.98888095, 0.09991401, 0.12295545],
       [0.65640803, 0.97131467, 0.08107003, 0.54513167, 0.72490344]])

In [56]:
a.reshape(10,1)

array([[0.33045311],
       [0.54236473],
       [0.98888095],
       [0.09991401],
       [0.12295545],
       [0.65640803],
       [0.97131467],
       [0.08107003],
       [0.54513167],
       [0.72490344]])

In [57]:
a.reshape(1,10)

array([[0.33045311, 0.54236473, 0.98888095, 0.09991401, 0.12295545,
        0.65640803, 0.97131467, 0.08107003, 0.54513167, 0.72490344]])

In [58]:
a.reshape(5,-1)

array([[0.33045311, 0.54236473],
       [0.98888095, 0.09991401],
       [0.12295545, 0.65640803],
       [0.97131467, 0.08107003],
       [0.54513167, 0.72490344]])

In [60]:
a.reshape(-1,5)

array([[0.33045311, 0.54236473, 0.98888095, 0.09991401, 0.12295545],
       [0.65640803, 0.97131467, 0.08107003, 0.54513167, 0.72490344]])

In [61]:
a.reshape(-1,10)

array([[0.33045311, 0.54236473, 0.98888095, 0.09991401, 0.12295545,
        0.65640803, 0.97131467, 0.08107003, 0.54513167, 0.72490344]])

# -Aggregate function

In [64]:
a.min()

0.0810700335647635

In [65]:
a.max()

0.9888809493974487

In [66]:
a.mean()

0.5063396091003489

In [67]:
a.std()

0.3234341854661436

In [68]:
a.var()

0.10460967232814777

In [72]:
np.percentile(a,60) #array a having .58% values are less than 60

0.5896422137315965

In [73]:
np.corrcoef(a)

array([[ 1., -1.,  1., -1.,  1.],
       [-1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.,  1.],
       [-1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.,  1.]])

# -Stacking

In [78]:
a=np.random.rand(1,5)
b=np.random.rand(1,5)
print (a)
print(b)

[[0.62684477 0.16383268 0.98220537 0.18868346 0.9448773 ]]
[[0.4502075  0.19020465 0.4032247  0.85461752 0.96139398]]


In [80]:
np.hstack([a,b])

array([[0.62684477, 0.16383268, 0.98220537, 0.18868346, 0.9448773 ,
        0.4502075 , 0.19020465, 0.4032247 , 0.85461752, 0.96139398]])

In [81]:
np.vstack([a,b])

array([[0.62684477, 0.16383268, 0.98220537, 0.18868346, 0.9448773 ],
       [0.4502075 , 0.19020465, 0.4032247 , 0.85461752, 0.96139398]])